# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wishlist-inspire"
client_id = "27c80af1600e58b82353ae2627cebe2d"
application_url = "https://yes-dg-transparent-rom.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://yes-dg-transparent-rom.trycloudflare.com/auth/callback",
  "https://yes-dg-transparent-rom.trycloudflare.com/auth/shopify/callback",
  "https://yes-dg-transparent-rom.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codeinspire-app-dev.myshopify.com"
