# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "wishlist-app"
client_id = "a3ced992a5e81ea643e85f3e163f06a1"
application_url = "https://funny-saint-sponsored-time.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://funny-saint-sponsored-time.trycloudflare.com/auth/callback",
  "https://funny-saint-sponsored-time.trycloudflare.com/auth/shopify/callback",
  "https://funny-saint-sponsored-time.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-checkout-ex.myshopify.com"
